// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMediaApp.api.Data;

#nullable disable

namespace SocialMediaApp.api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251028184127_SeedingData")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocialMediaApp.api.Entities.AppUser", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            PasswordHash = new byte[] { 0 },
                            PasswordSalt = new byte[] { 0 },
                            UserName = "bobby"
                        },
                        new
                        {
                            ID = 2,
                            PasswordHash = new byte[] { 0 },
                            PasswordSalt = new byte[] { 0 },
                            UserName = "tom"
                        },
                        new
                        {
                            ID = 3,
                            PasswordHash = new byte[] { 0 },
                            PasswordSalt = new byte[] { 0 },
                            UserName = "jane"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
